# Configuration for SLAM Toolbox in Online, Asynchronous Mode
slam_toolbox:
  ros__parameters:
    # PLUGIN PARAMETERS
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_strategy: "LEVENBERG_MARQUARDT"
    ceres_dogleg_type: "TRADITIONAL_DOGLEG"
    ceres_loss_function: "None"

    # ROS PARAMETERS
    # These must match the frames and topics from your robot and Gazebo bridge
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link" # Or "base_footprint" depending on your URDF
    scan_topic: "/scan"
    
    # GENERAL PARAMETERS
    use_scan_matching: true
    use_map_saving: true
    map_file_name: "my_map" # Base name for saved maps
    
    # MAP PARAMETERS
    resolution: 0.05 # Meters per pixel
    map_update_interval: 5.0 # Seconds
    
    # SCAN MATCHER PARAMETERS
    # Adjust these to tune performance
    minimum_travel_distance: 0.2 # meters
    minimum_travel_heading: 0.17 # radians (about 10 degrees)
    loop_search_maximum_distance: 10.0